name: Deploy preview to Firebase Hosting on PR

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install & Build
        run: |
          npm install
          npm run build

      - name: Deploy to Firebase Preview (target: kitchen)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOUNTAINMEDICINE_6E572 }}
          projectId: mountainmedicine-6e572
          target: kitchen
          expires: 7d
